Misc changes v2
astarte-platform/astarte-device-sdk-rust pull request #10
Opened 2021-10-17 13:55 UTC by shikoku1

changes:

- add sanity checks when receiving data
- database check before sending properties
- bugfix database for deceiving data
- documentation
- tests

2021-11-05 11:35 UTC, rbino approved these changes

2021-11-17 16:39 UTC, bettio requested changes

2021-11-17 16:39 UTC, bettio commented on examples/interfaces/org.astarte-platform.genericsensors.AvailableSensors.json
> +}
missing new line at the end of file

2021-11-17 16:39 UTC, bettio commented on src/interfaces.rs
> +                    "endpoint": "/bottone",
italian leftover

2021-11-17 17:54 UTC, bettio approved these changes

2021-11-22 15:36 UTC, merged