Update bson dependency
astarte-platform/astarte-device-sdk-rust pull request #14
Opened 2021-11-23 13:48 UTC by shikoku1

We have to specialize the `from_bson_array` macro for `DateTimeArray` because bson has its own datetime type that doesn't support `FromIterator`

2021-11-25 09:57 UTC, harlem88 approved these changes

2021-11-25 11:26 UTC, rbino requested changes
Please add to the commit message and PR description the implications of the update (e.g. the fact that you had to add some specialization for the DateTimeArray type).

2021-11-25 17:23 UTC, shikoku1 commented
It's already documented in the code, there are no implications for the users

2021-11-30 14:29 UTC, rbino approved these changes

2021-11-30 14:29 UTC, merged