Remove `ignore_ssl_errors` and bump up Astarte version
astarte-platform/astarte-device-sdk-rust pull request #141
Opened 2023-02-17 17:39 UTC by sorru94

Some small fixes:
- Removes the not necessary `ignore_ssl_errors` flag in the end-to-end tests.
- Handle correctly a failure of `POST` or `DELETE` HTTPS requests.
- Bump up version of Astarte in CI to `1.0.04`

2023-03-08 11:07 UTC, FrancescoVaiani requested changes
I could not remember what the status code 204 stands for. 
Maybe we can begin to slowly replace the status codes with the Reqwest StatusCode enum.

2023-03-08 11:07 UTC, FrancescoVaiani commented on tests/e2etest/main.rs
> +    if response.status() != 200 {
Can we replace 200 with the Reqwest status code enum?
```suggestion
    if response.status() != StatusCode::Ok{
```

2023-03-08 11:07 UTC, FrancescoVaiani commented on tests/e2etest/main.rs
> +    if response.status() != 204 {
Can we replace 204 with the Reqwest status code enum?
```suggestion
    if response.status() != StatusCode::NoContent{
```

2023-03-10 08:49 UTC, sorru94 commented
> I could not remember what the status code 204 stands for. Maybe we can begin to slowly replace the status codes with the Reqwest StatusCode enum.

I noticed that in the `registration.rs` and `pairing.rs` modules we use `http::StatusCode` instead of `reqwest::StatusCode`.
I think it would be better to use the `reqwest::StatusCode` everywhere as we always compare to a result from `reqwest`.

2023-04-13 07:20 UTC, harlem88 approved these changes

2023-04-13 07:21 UTC, merged