feat(derive): update the aggregate derive macro
astarte-platform/astarte-device-sdk-rust pull request #236
Opened 2023-09-11 12:21 UTC by joshuachp

- Update `syn` to version 2.0 and refactor the code to support the breaking changes for the new major version.
- Restructure the code to use the `Parse` trait to get the information from the `TokenStream`.
- Do not panic, but return a compile error through the `syn::Error` which are converted in `compile_error!(..)`.
- Check the name and value from the derive attribute, before only the value was checked.
- Require the generics on the struct to implement `TryInto<AstarteType>` so so we can have generics in the aggregate.
- Use `quote_spanned` for the conversion for better error messages.
- Use the full path `astarte_device_sdk::AggregateDerive` for the trait impl to prevent conflicts with the trait.

2023-09-13 13:45 UTC, joshuachp commented
> The changes regarding the derive crate look good. But I don't understand why the workspace commit (`1eb105ff9d1e662343b3674d72b0e42136546728`) is present in this PR.

FTR: the workspace is needed to make the CI run also for the derive crate, before was ignored

2023-09-14 12:21 UTC, sorru94 approved these changes

2023-09-15 07:12 UTC, harlem88 requested changes

2023-09-15 07:12 UTC, harlem88 commented on .cargo/config.toml
> +# This file is part of Edgehog.
```suggestion
# This file is part of Astarte.
```

2023-09-15 07:48 UTC, joshuachp commented on .cargo/config.toml
> +# This file is part of Edgehog.
Fixed

2023-10-04 14:38 UTC, harlem88 approved these changes

2023-10-18 10:05 UTC, harlem88 approved these changes

2023-10-18 10:37 UTC, merged