feature(store): add a wriatable path option
astarte-platform/astarte-device-sdk-rust pull request #314
Opened 2024-04-03 14:36 UTC by joshuachp

Add a storable path for the SDK. This let's us implement the following:

- Storing the credential secret and using a paring token for authentication
- Reusing a created SSL certificate for the device

2024-04-22 13:08 UTC, rgallor requested changes

2024-04-23 14:19 UTC, joshuachp commented on src/transport/mqtt/config/connection.rs
> +        self.create_and_store(client, &certificate_file, &private_key_file)
It was to better separate the function, at line 103 we check that we have the store directory. If we don't, we create a new one and return  it immediatelly, otherwhise we call the create and store

2024-04-23 14:20 UTC, joshuachp commented on src/transport/mqtt/config/connection.rs
> +        self.create_and_store(client, &certificate_file, &private_key_file)
I will try to separate the function to make this more clear, if you can please tell me what you think about the new structure

2024-04-23 14:21 UTC, joshuachp commented on src/transport/mqtt/config/connection.rs
> +    async fn create_and_store(
Agread, doing the refactor as commented above 👍🏻

2024-04-23 15:37 UTC, harlem88 commented on src/transport/mqtt/config/connection.rs
> +        self.create_and_store(client, &certificate_file, &private_key_file)
ok I agree with the new structure

2024-04-24 09:38 UTC, rgallor approved these changes

2024-04-24 10:38 UTC, merged