Prepare release v0.6.6
astarte-platform/astarte-device-sdk-rust pull request #348
Opened 2024-05-24 15:49 UTC by rgallor

2024-05-24 15:59 UTC, harlem88 approved these changes

2024-05-27 09:56 UTC, joshuachp approved these changes

2024-05-27 10:22 UTC, harlem88 requested changes

2024-05-27 10:22 UTC, harlem88 commented on CHANGELOG.md
> +## [0.6.6] - 2024-05-24
```suggestion
## [0.6.6] - 2024-05-27
```

2024-05-27 10:22 UTC, harlem88 commented on astarte-device-sdk-derive/CHANGELOG.md
> +## [0.6.6] - 2024-05-24
```suggestion
## [0.6.6] - 2024-05-27
```

2024-05-27 10:35 UTC, harlem88 approved these changes

2024-05-27 10:36 UTC, merged