chore(doc): improve the documentation for docs.rs
astarte-platform/astarte-device-sdk-rust pull request #373
Opened 2024-09-04 15:53 UTC by joshuachp

2024-09-05 08:10 UTC, rgallor approved these changes

2024-09-05 09:04 UTC, rgallor commented
LGTM, just fix the clippy warnings

2024-09-09 13:26 UTC, joshuachp commented
Fixed the nightly warning, I re-done the fixes since the commit in master cannot be cherry-picked.

2024-09-09 15:27 UTC, harlem88 requested changes

2024-09-09 15:27 UTC, harlem88 commented on assets/images/favico.svg
Remove the logo for now.

2024-09-09 15:46 UTC, harlem88 requested changes

2024-09-09 15:46 UTC, harlem88 commented on .reuse/dep5
> +License: CC0-1.0
```suggestion
```

2024-09-09 15:48 UTC, joshuachp commented
Removed the commit with the favicon

2024-09-09 15:50 UTC, harlem88 approved these changes

2024-09-09 15:56 UTC, merged