feat(derive): add allow unset for Optional values
astarte-platform/astarte-device-sdk-rust pull request #378
Opened 2024-09-12 12:31 UTC by joshuachp

Add the attribute `allow_unset` to make the value of an individual property be wrapped in an `Option` when the value is un `Value::Unset`.

2024-09-19 08:48 UTC, rgallor approved these changes

2024-09-20 07:39 UTC, harlem88 requested changes

2024-09-20 07:39 UTC, harlem88 commented on astarte-device-sdk-derive/src/event.rs
> +
Remove the double new line
```suggestion
```

2024-09-24 08:52 UTC, harlem88 approved these changes

2024-09-24 08:52 UTC, merged