feat(webpki): use Mozilla webpki root certificates
astarte-platform/astarte-device-sdk-rust pull request #396
Opened 2024-12-09 17:02 UTC by rgallor

Avoid using native certs when webpki feature is enabled

2024-12-12 08:47 UTC, harlem88 reviewed
Add a few lines to the changelog

2024-12-13 07:56 UTC, harlem88 approved these changes

2024-12-13 14:44 UTC, joshuachp requested changes

2024-12-13 14:44 UTC, joshuachp commented on src/transport/mqtt/config/transport.rs
> +    root_cert_store: Option<RootCertStore>
```suggestion
    root_cert_store: Option<Arc<RootCertStore>>
```

2025-01-09 14:40 UTC, joshuachp requested changes

2025-01-09 14:40 UTC, joshuachp commented on src/transport/mqtt/config/tls.rs
> +        let rustls_native_certs::CertificateResult { certs, errors, .. } =
```suggestion
        let res =
```
I think restructuring the result hinders the readability

2025-01-27 09:04 UTC, joshuachp commented on CHANGELOG.md
> +- Bump MSRV to 1.78.0 [#395](https://github.com/astarte-platform/astarte-device-sdk-rust/pull/395).
Good linking 🚀

2025-01-27 09:09 UTC, joshuachp commented on src/transport/mqtt/connection.rs
> +        };
I'm not too sure with this change, I'm worried this will create an infinite loop.

2025-01-27 09:22 UTC, joshuachp requested changes

2025-01-27 09:22 UTC, joshuachp commented on src/transport/mqtt/connection.rs
> +        };
I think the best course of action is that the transport provider should read the root cert store in creation, so we can move the error during configuration and not risk looping indefinitely during reconnection.

2025-01-27 09:24 UTC, joshuachp requested changes

2025-01-27 09:24 UTC, joshuachp commented on src/transport/mqtt/config/mod.rs
>          );
We can add a method `configure`, called here, that will read the cert store and return the `TransportProvider`.

2025-01-27 09:26 UTC, joshuachp commented on src/transport/mqtt/config/mod.rs
>          );
This way we can remove the `Option` around the Cert Store and the error returned by the api_tls_config call.

2025-01-28 14:49 UTC, harlem88 requested changes

2025-01-28 14:49 UTC, harlem88 commented on src/transport/mqtt/pairing.rs
> +    tls: ClientConfig,
What do you think about call it `tls_config`?
```suggestion
    tls_config: ClientConfig,
```

2025-01-28 15:00 UTC, rgallor commented on src/transport/mqtt/pairing.rs
> +    tls: ClientConfig,
LGTM

2025-01-28 15:29 UTC, harlem88 requested changes

2025-01-28 15:29 UTC, harlem88 commented on src/transport/mqtt/pairing.rs
> +        tls: ClientConfig,
sorry, same here
```suggestion
        tls_config: ClientConfig,
```

2025-01-30 10:54 UTC, harlem88 approved these changes

2025-02-04 09:26 UTC, joshuachp requested changes

2025-02-19 16:25 UTC, joshuachp requested changes

2025-02-19 16:25 UTC, joshuachp commented on src/transport/mqtt/config/transport.rs
>      }
```suggestion
    pub(crate) fn new(
        pairing_url: Url,
        credential_secret: String,
        store_dir: Option<PathBuf>,
        insecure_ssl: bool,
        root_cert_store: RootCertStore,
    ) -> Self {
        Self {
            pairing_url,
            credential_secret,
            store_dir,
            insecure_ssl,
            root_cert_store: Arc::new(root_cert_store),
        }
    }
```

We can remove it if not used anymore

2025-02-26 14:04 UTC, joshuachp approved these changes

2025-02-26 14:10 UTC, merged