Feature/get properties
astarte-platform/astarte-device-sdk-rust pull request #399
Opened 2024-12-18 16:00 UTC by lucaato

2025-01-02 14:29 UTC, rgallor requested changes

2025-01-02 14:29 UTC, rgallor commented on src/transport/grpc/mod.rs
> +/// Device owned properties wont be stored and will be requested to the message hub server.
typo won't

2025-01-02 14:29 UTC, rgallor commented on src/transport/grpc/mod.rs
> +        }
you could increase readability with:
```suggestion
// we only store server-owned properties
        if prop.ownership.is_device() { // or use   !prop.ownership.is_server()
            return Ok(());
        }

        self.store
            .store_prop(prop)
            .await
            .map_err(GrpcStoreError::from_err)
```

2025-01-02 14:29 UTC, rgallor commented on src/transport/grpc/mod.rs
> +        }
the same stands for all the other methods where the else condition returns Ok(())

2025-01-02 14:29 UTC, rgallor commented on src/transport/mod.rs
> +    //type Store: PropertyStore;
this shouldn't be necessary anymore, should it?

2025-01-07 11:04 UTC, rgallor requested changes

2025-01-07 11:04 UTC, rgallor commented on src/transport/grpc/mod.rs
> +            .collect_vec())
Just for greater readability, I'd extract this value into a variable and return Ok(var)

2025-01-07 11:04 UTC, rgallor commented on src/transport/grpc/mod.rs
> +        // if to get properties only when connecting
I don't get this comment

2025-01-28 10:30 UTC, rgallor requested changes

2025-01-28 10:30 UTC, rgallor commented on src/store/mod.rs
> +impl<'a, S, T> From<&'a StoredProp<S, T>> for StoreInterfaceData<&'a str>
You could use here the same Generic notation used in the definition of `StoredProp` (which is <S, V> rather than <S, T>)

2025-01-28 11:14 UTC, rgallor requested changes

2025-01-28 11:14 UTC, rgallor commented on src/transport/grpc/mod.rs
> +            .collect_vec();
You could directly use the `append` method of vec (thus avoid importing `Itertools`:

```suggestion
let mut merged_properties = server_result?;
merged_properties.append(&mut device_result?);
```

2025-01-28 11:29 UTC, lucaato commented on src/transport/grpc/mod.rs
> +            .collect_vec();
This avoids having a mut variable, itertools is already imported anyways, are you sure anyway about the change ?

2025-01-28 11:56 UTC, rgallor commented on src/transport/grpc/mod.rs
> +            .collect_vec();
It would have sense using `chain` with iterators if you don't have to collect at the end. Also, append does not clone but rather move elements from one vec to the other

2025-01-28 13:23 UTC, rgallor approved these changes

2025-01-28 14:23 UTC, lucaato commented on src/transport/grpc/mod.rs
> +            .collect_vec();
In the end I applied the change

2025-01-29 16:16 UTC, lucaato commented
After a bit of irl discussion and a bit of help from @joshuachp we refactored out the `WrapStore` trait, along with some changes to the device builder that should be small enough to fit in this pr.

2025-01-29 16:23 UTC, lucaato commented on src/store/mod.rs
> +pub struct StoreInterfaceData<S = String> {
Maybe InterfaceData or InterfaceInfo, I do not especially like Record as a suffix because it makes it look like a db stored record even if that's not the case.

2025-01-29 16:51 UTC, lucaato commented on src/store/mod.rs
> +pub struct StoreInterfaceData<S = String> {
Settled on IntefaceInfo.

2025-01-30 10:45 UTC, harlem88 requested changes

2025-01-30 10:45 UTC, harlem88 commented on src/transport/grpc/convert.rs
> +pub fn map_property_to_astarte_type(
Is this function need to be `pub`? Maybe is keep only visible to the crate
```suggestion
pub(crate) fn map_property_to_astarte_type(
```

2025-01-30 10:45 UTC, harlem88 commented on src/transport/grpc/convert.rs
> +pub fn map_set_stored_properties(
same above

2025-01-30 10:45 UTC, harlem88 commented on src/transport/grpc/mod.rs
> +/// Store wrapper designed specifically for the grpc connection
Grpc Store?
```suggestion
/// GrpcStore designed specifically for the grpc connection
```

2025-01-30 10:55 UTC, rgallor approved these changes

2025-01-30 11:01 UTC, rgallor requested changes

2025-01-30 11:01 UTC, rgallor commented on src/store/mod.rs
> +    fn load_prop<I>(
you could use generic `I` also in the `PropertyStore` implementation for `MemoryStore` and `SqliteStore` (where instead you are using `S`)

2025-01-30 11:54 UTC, lucaato commented on src/transport/grpc/mod.rs
> +/// Store wrapper designed specifically for the grpc connection
Since it would have been a bit repetitive, I changed it this way
```suggestion
/// Store implementation designed specifically for the grpc connection
```

2025-01-30 11:57 UTC, lucaato commented on src/transport/grpc/convert.rs
> +pub fn map_property_to_astarte_type(
Yes they can probably be carte public if the message hub does not use them, and I don't think it does.

2025-01-30 12:06 UTC, lucaato commented on src/store/mod.rs
> +    fn load_prop<I>(
I think `S` is more correct since the `StoredProp` also uses that notation.

2025-01-30 14:13 UTC, rgallor requested changes

2025-01-30 14:13 UTC, rgallor commented on Cargo.toml
> +astarte-message-hub-proto = { git = "https://github.com/astarte-platform/astarte-message-hub-proto.git", rev = "370be08ff90236a25b15af6e27d5363739566f2f" }
You could update the rev commit since the master branch of the astarte-message-hub-proto repo has been updated, however the new modifications do not impact this functionality (so feel free to leave this rev)

2025-01-30 15:01 UTC, lucaato commented on Cargo.toml
> +astarte-message-hub-proto = { git = "https://github.com/astarte-platform/astarte-message-hub-proto.git", rev = "370be08ff90236a25b15af6e27d5363739566f2f" }
I think I will leave it as is and bump it in the test refactor pr

2025-01-30 15:16 UTC, rgallor approved these changes

2025-01-30 15:56 UTC, harlem88 approved these changes

2025-02-03 09:14 UTC, joshuachp requested changes

2025-02-03 09:14 UTC, joshuachp commented on src/interfaces.rs
> +/// Public in a private module that is never exported
```suggestion
```

2025-02-03 09:18 UTC, joshuachp commented on src/store/wrapper.rs
> +// TODO could this be a blanket implementation for every S that returns dyn error
```suggestion
```

The error could be re-worked if we change the Store trait. I don't think an extension trait would be needed though.

2025-02-03 09:20 UTC, joshuachp commented on src/store/mod.rs
> +}
Why do we need this to be a String and not an &str? Since it will not be modified.

2025-02-03 09:23 UTC, joshuachp commented on src/store/mod.rs
> +}
It will also simplify all the generics in the trait

2025-02-03 09:27 UTC, joshuachp commented on src/transport/grpc/mod.rs
> +/// Store implementation designed specifically for the grpc connection
We should separate this into it's own store module

2025-02-03 09:31 UTC, joshuachp requested changes

2025-02-03 09:31 UTC, joshuachp commented on src/transport/grpc/mod.rs
> +    pub(crate) client: Arc<Mutex<MsgHubClient>>,
```suggestion
    pub(crate) client: MsgHubClient,
```

2025-02-03 09:31 UTC, joshuachp commented on src/transport/grpc/mod.rs
> +    pub(crate) client: Arc<Mutex<MsgHubClient>>,
I think you can achieve this by modifying the store trait. Since it's Clone and should be accessed by one instance exclusively.

2025-02-03 10:47 UTC, lucaato commented on src/store/mod.rs
> +}
If it was a &str it would clutter some struct it is included in. For example look at `ClientMessage` in `src\connection.rs`. It would be messier to manage. We need it in the Unset variant because then we need to access the store. Are you suggesting that, since unsets should only be performed on device owned interfaces, we just assume it's a device interface ? To avoid having the InterfaceInfo struct inside the ClientMessage struct

2025-02-03 12:45 UTC, lucaato commented on src/transport/grpc/mod.rs
> +    pub(crate) client: Arc<Mutex<MsgHubClient>>,
I'll try this, if it requires too many changes this should be done in another pr.

2025-02-04 10:25 UTC, lucaato commented on src/transport/grpc/mod.rs
> +    pub(crate) client: Arc<Mutex<MsgHubClient>>,
To do this i would need to modify the public interface of the sdk to accept an &mut self or wrap the store in a mutex from the outside, I don't think this should be done in this pr.

2025-02-04 10:28 UTC, rgallor commented on src/transport/grpc/store.rs
> + * Copyright 2023 SECO Mind Srl
since you are introducing this file, I'd change the year accordingly

2025-02-04 10:59 UTC, joshuachp commented on src/transport/grpc/mod.rs
> +    pub(crate) client: Arc<Mutex<MsgHubClient>>,
You're right, after a more careful consideration I don't think it's worth to change all the client for this change. 

I think we should reconsider this when we want to move the sender to the client.

2025-02-04 11:09 UTC, joshuachp requested changes

2025-02-04 11:09 UTC, joshuachp commented on src/validate.rs
> +    pub(crate) interface: InterfaceInfo,
```suggestion
    pub(crate) interface: String,
```

2025-02-04 11:09 UTC, joshuachp commented on src/validate.rs
> +    pub(crate) interface: InterfaceInfo,
This is only sent by the device

2025-02-28 09:01 UTC, lucaato commented on src/store/mod.rs
> +}
Removed the generic parameter

2025-02-28 09:29 UTC, lucaato commented on src/validate.rs
> +    pub(crate) interface: InterfaceInfo,
In the end I created a From<ValidatedUnset> for Interface info so that the interface of the store can use it consistently in every method

2025-02-28 11:10 UTC, joshuachp requested changes

2025-02-28 11:10 UTC, joshuachp commented on src/store/mod.rs
> +}
We should add a `PropertyStore` struct to make it simpler to add more arguments to the store functions. It should also implement `Deref` with target `InterfaceInfo` and have public getters for all the fields.

2025-03-04 08:44 UTC, lucaato commented on src/store/mod.rs
> +}
I've implemented the `PropertyInfo` struct, for now I've left out the major version of the interface since in the store it is used in only one method, it can be added in the feature.

2025-03-04 08:50 UTC, joshuachp commented on src/store/mod.rs
> +}
I would still add the property info to the struct, otherwise it defeats the purpose of adding arguments without breaking compatibility.

2025-03-04 08:55 UTC, joshuachp requested changes

2025-03-04 08:55 UTC, joshuachp commented on src/store/mod.rs
> +    pub(crate) path: &'a str,
```suggestion
    interface_info: InterfaceInfo<'a>,
    path: &'a str,
```

2025-03-04 08:55 UTC, joshuachp commented on src/store/mod.rs
> +    pub(crate) ownership: Ownership,
```suggestion
    name: &'a str,
    ownership: Ownership,
```

2025-03-04 08:56 UTC, joshuachp commented on src/store/mod.rs
> +    pub(crate) path: &'a str,
So we are forced to use the public methods in the SDK

2025-03-04 08:59 UTC, joshuachp commented on src/store/mod.rs
> +}
And what do we think of calling them PropPath and PropInterface

2025-03-04 13:26 UTC, rgallor commented on src/store/mod.rs
> +}
Yes, `PropertyInterface`  (or `PropInterface`) sounds good to me

2025-03-04 13:39 UTC, joshuachp commented on src/store/mod.rs
> +}
For me it's the same 👍🏻

2025-03-04 16:41 UTC, lucaato commented on src/transport/grpc/store.rs
> +        }
Until we have a way for the message hub to avoid client overriding each other properties we want to return only the properties of the message hub which are guaranteed to be updated if updated by another client.

2025-03-04 16:58 UTC, joshuachp commented on src/transport/grpc/store.rs
> +        }
In the current state, since we unfortunately have no way to prevent the properties to be overwritten I propose the following to prevent them to be lost when disconnected.

- Wen a property is set/unset/deleted we also make the change to the Store
- When we load a property we must ask it to the Message Hub because it can be set by other devices/applications
- When reconnecting we send all the Device properties in the store

This way we do not lose the data that we tried to send while offline. What do you think @harlem88

2025-03-05 08:45 UTC, lucaato commented on src/transport/grpc/convert.rs
> +#[derive(thiserror::Error, Debug, Clone)]
I removed it

2025-03-05 09:40 UTC, joshuachp commented on src/transport/grpc/store.rs
> +    pub(crate) store: S,
```suggestion
```

2025-03-05 09:40 UTC, joshuachp commented on src/transport/grpc/store.rs
> +            .map_err(GrpcStoreError::from_err)
```suggestion
    Ok(())
```

2025-03-05 09:40 UTC, joshuachp commented on src/transport/grpc/store.rs
> +            .map_err(GrpcStoreError::from_err)
The property should be stored on the message hub

2025-03-05 09:40 UTC, joshuachp commented on src/transport/grpc/store.rs
> +        }
```suggestion
```
Same as above, as discussed we should ask the Message Hub

2025-03-05 14:11 UTC, joshuachp requested changes

2025-03-05 14:11 UTC, joshuachp commented on src/transport/grpc/convert.rs
> +}
Do we want to error on unset in the store, or should we filter them?

2025-03-05 14:14 UTC, lucaato commented on src/validate.rs
> +}
I wanted to keep it near the validate method to show clearly that the constructor only allows device properties

2025-03-05 14:31 UTC, lucaato commented on src/transport/grpc/convert.rs
> +}
This was something we discussed and we decided that the message hub should not return unset values if I'm not mistaken. This is probably something that from the server side handles too, @rgallor do you remember something similar ?

2025-03-05 14:59 UTC, lucaato commented on src/transport/grpc/store.rs
> +    }
Used a from impl

2025-03-05 15:00 UTC, lucaato commented on src/transport/grpc/convert.rs
> +}
makes sense

2025-03-06 10:07 UTC, joshuachp approved these changes

2025-03-10 11:51 UTC, lucaato commented on src/builder.rs
> +    C: RetentionOverrideConfig,
Added this trait bound and trait to allow the grpc connection to disable the volatile retention by setting the capacity to `0`.

2025-03-10 11:55 UTC, lucaato commented on src/builder.rs
> +    pub fn volatile_retention(mut self, items: usize) -> Self {
I moved this method here so that the user can call it only after setting the connection config to `MqttConfig`. She won't be able to call this method when the connection config is `GrpcConfig` as the config would be overridden anyway.

2025-03-10 12:04 UTC, joshuachp requested changes

2025-03-10 12:04 UTC, joshuachp commented on src/retention/memory.rs
> +            store: VecDeque::with_capacity(1),
I don't think this is necessary or too good for the store, if we create a new `VolatileStore` without capacity we don't want to allocate nothing and then set the appropriate capacity

2025-03-10 12:06 UTC, joshuachp commented on src/retention/memory.rs
> +            store: VecDeque::with_capacity(1),
Furthermore, having just one element is not that useful for the store, but it still needs to be allocated.

2025-03-10 12:18 UTC, rgallor requested changes

2025-03-10 13:23 UTC, lucaato commented on src/retention/memory.rs
> +            store: VecDeque::with_capacity(1),
Ok

2025-03-10 13:59 UTC, rgallor requested changes

2025-03-10 13:59 UTC, rgallor commented on src/builder.rs
> +    C: RetentionOverrideConfig,
make sense!

2025-03-10 13:59 UTC, rgallor commented on src/retention/memory.rs
> +        store.push(ctx.next(), info.clone());
are all of them necessary for the test?

2025-03-10 13:59 UTC, rgallor commented on src/store/sqlite/mod.rs
> +            .delete_interface_props(interface.name.as_ref())?;
you could directly use `interface.name` or `interface.name()` rather than calling `as_ref()`

2025-03-10 13:59 UTC, rgallor commented on src/store/sqlite/mod.rs
> +        self.with_reader(|reader| reader.interface_props(interface.name.as_ref()))
same here

2025-03-10 13:59 UTC, rgallor commented on src/store/sqlite/mod.rs
> +        self.with_reader(|reader| reader.interface_props(interface.name.as_ref()))
same here

2025-03-10 13:59 UTC, rgallor commented on src/store/sqlite/mod.rs
> +            .delete_prop(property.name.as_ref(), property.path)?;
also here

2025-03-10 13:59 UTC, rgallor commented on src/store/sqlite/mod.rs
> +            .unset_prop(property.name.as_ref(), property.path)?;
also here

2025-03-10 13:59 UTC, rgallor commented on src/store/sqlite/mod.rs
> +            self.with_reader(|reader| reader.load_prop(property.name.as_ref(), property.path))?;
also here

2025-03-10 14:28 UTC, lucaato commented on src/retention/memory.rs
> +            }
It was to avoid having multiple if branching the main path... I don't think it changes much either way but if it is not full we already know we can push an element so I wouldn't move it.

2025-03-10 14:29 UTC, lucaato commented on src/retention/memory.rs
> +        store.push(ctx.next(), info.clone());
It is just to show that no amounts of pushing will have effect but it's the same

2025-03-10 14:31 UTC, rgallor commented on src/store/mod.rs
> +    }
I would use a single method like the following:


```suggestion
    pub(crate) fn new_unchecked(interface_info: impl Into<PropertyInterface<'a>>, path: &'a str) -> Self {
        Self {
            interface_info: interface_info.into(),
            path,
        }
    }
```

2025-03-10 14:46 UTC, lucaato commented on src/store/mod.rs
> +    }
No, I'd prefer to keep them separated since `new_unchecked` could be considered an `unsafe` method because you have to make sure that the interface you are passing is actually a property interface but we have no way of knowing. At the same time `with_property_path` is checked by our other methods to receive an input property interface.
This is only used inside the crate so it's not a big deal, but it would be better to keep them separated IMO. If this doesn't make sense to most of us I can remove it.

2025-03-17 13:44 UTC, harlem88 requested changes
LGTM

2025-03-17 13:44 UTC, harlem88 commented on src/transport/grpc/store.rs
> +/// device owned properies. We only want to store and load from the store server owned properties.
Nit: Change to `properties`
```suggestion
/// device owned properties. We only want to store and load from the store server owned properties.
```

2025-03-17 14:19 UTC, harlem88 approved these changes

2025-03-17 14:34 UTC, merged