chore(ci): add job to warm cache and install deps
astarte-platform/astarte-device-sdk-rust pull request #400
Opened 2024-12-20 09:10 UTC by joshuachp

Fix missing deps in the new version of Ubuntu 24.04 and add a job to warm the cache.

2024-12-20 09:42 UTC, harlem88 approved these changes

2024-12-20 10:59 UTC, lucaato commented on .github/workflows/warm-caches.yaml
> +# This file is part of Astarte.
nit: The name for this file could be `warmup-cache`

2024-12-20 13:29 UTC, lucaato approved these changes

2025-01-02 11:24 UTC, rgallor approved these changes

2025-01-09 14:45 UTC, harlem88 requested changes

2025-01-09 14:45 UTC, harlem88 commented on .github/workflows/multi-platform.yaml
> +# Copyright 2024 SECO Mind Srl
```suggestion
# Copyright 2025 SECO Mind Srl
```

2025-01-09 14:45 UTC, harlem88 commented on .github/workflows/warmup-caches.yaml
> +# Copyright 2024 SECO Mind Srl
```suggestion
# Copyright 2025 SECO Mind Srl
```

2025-01-09 15:21 UTC, harlem88 approved these changes

2025-01-10 09:25 UTC, merged