Receive data validation bug fix
astarte-platform/astarte-device-sdk-rust pull request #51
Opened 2022-05-26 14:53 UTC by FrancescoVaiani

In the case of a server-owned longinteger mapping, Astarte sends an integer number if the value is small enough.
This behavior was not taken into account during the data validation. 
A condition was add in the `eq` function that compares the type of the data received with the mapping type.
Added some tests.

2022-05-30 08:00 UTC, harlem88 requested changes

2022-05-30 08:00 UTC, harlem88 commented on src/types.rs
> +        if other == &crate::interface::MappingType::LongInteger {
Specify at top of function the `use` declaration for better readability.
``` Rust
use crate::interface::MappingType 
``` 
....
``` Rust
if other == &MappingType::LongInteger
```

2022-05-31 08:00 UTC, harlem88 approved these changes

2022-07-01 10:34 UTC, Annopaolo approved these changes

2022-07-01 10:46 UTC, merged