Implement registration and uuid generation
astarte-platform/astarte-device-sdk-rust pull request #6
Opened 2021-09-24 23:36 UTC by shikoku1

2021-09-28 08:15 UTC, harlem88 approved these changes

2021-09-30 10:56 UTC, rbino requested changes
@shikoku1 please apply 0e418faa23f3d791292e80c9300b192c144968c1 and 8d8398891b49d1495aa27b77a8134be6f952a430 as fixups to 94e322a9edcc3524c1dfa29e8e60d0be2def48f6

2021-09-30 13:08 UTC, rbino approved these changes

2021-09-30 13:14 UTC, bettio approved these changes

2021-09-30 13:15 UTC, merged