Add dynamic interface remove
astarte-platform/astarte-device-sdk-rust pull request #79
Opened 2022-11-16 11:02 UTC by FrancescoVaiani

Add the capability to remove an interface from introspection after device connection.

Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

2022-11-17 10:19 UTC, harlem88 requested changes

2022-11-17 10:19 UTC, harlem88 commented on src/lib.rs
> +            .ok_or_else(|| AstarteError::SendError("Interface doesn't exist".into()))?;
1. Use `to_string()` to convert str to String.
2. Maybe is better add a new error to `interface::Error` like `InterfaceNotFound`  and add it among the `AstarteError` enum.

2022-11-17 10:19 UTC, harlem88 commented on src/lib.rs
> +        Ok(false)
Why do you always return false here?

2022-11-25 10:50 UTC, Annopaolo approved these changes

2022-11-25 11:08 UTC, harlem88 approved these changes

2022-11-30 13:09 UTC, harlem88 approved these changes

2022-11-30 14:44 UTC, Annopaolo approved these changes

2022-12-02 11:07 UTC, merged