Refactor send object api
astarte-platform/astarte-device-sdk-rust pull request #8
Opened 2021-09-27 13:37 UTC by shikoku1

hashmap was bad so we use a struct

2021-09-28 17:12 UTC, harlem88 approved these changes

2021-09-30 10:52 UTC, rbino approved these changes

2021-09-30 10:58 UTC, rbino requested changes
Actually @shikoku1 those two commits can be squashed too, please do so

2021-10-01 13:02 UTC, rbino approved these changes

2021-10-04 11:04 UTC, bettio approved these changes

2021-10-04 11:06 UTC, merged