Improved examples
astarte-platform/astarte-device-sdk-rust pull request #93
Opened 2022-12-20 15:11 UTC by sorru94

This PR aims to improve the examples. 
The following changes are included:
- Moving each example into its own folder
- Adding readmes for all the examples, plus a common one for the shared steps
- Removing the database example as it didn't have any significant difference from the device properties example
- Generic improvements over all the examples

2023-05-02 10:59 UTC, joshuachp requested changes

2023-05-02 10:59 UTC, joshuachp commented on examples/individual_datastream/main.rs
> +                    }
We could drop the nom dependency to simplify the example

```suggestion
                let mut iter = input.splitn(3, '/').skip(1);
                let led_id = iter.next().and_then(|id| id.parse::<u16>().ok())?;

                match iter.next() {
                    Some("enable") => {
                        println!(
                            "Received new enable datastream for LED number {}. LED status is now {}",
                            led_id,
                            if var == true { "ON" } else { "OFF" }
                        );
                    }
                    Some("intensity") => {
                        let value: f64 = var.try_into().unwrap();
                        println!(
                            "Received new intensity datastream for LED number {}. LED intensity is now {}",
                            led_id, value
                        );
                    }
                    _ => {}
                }
```

2023-05-02 10:59 UTC, joshuachp commented on examples/individual_datastream/main.rs
> +};
```suggestion
```

2023-05-02 10:59 UTC, joshuachp commented on Cargo.toml
> +nom = "7.1.1"
```suggestion
```

2023-05-02 10:59 UTC, joshuachp commented on examples/individual_properties/main.rs
> +};
```suggestion

```

2023-05-02 10:59 UTC, joshuachp commented on examples/individual_properties/main.rs
> +                    }
```suggestion

                    let mut iter = input.splitn(3, '/').skip(1);
                    let sensor_id = iter.next().and_then(|id| id.parse::<u16>().ok())?;

                    match iter.next() {
                        Some("enable") => {
                            println!(
                                "Sensor number {} has been {}",
                                sensor_id,
                                if var == true { "ENABLED" } else { "DISABLED" }
                            );
                        }
                        Some("samplingPeriod") => {
                            let value: i32 = var.try_into().unwrap();
                            println!("Sampling period for sensor {} is {}", sensor_id, value);
                        }
                        _ => {}
                    }
```

2023-05-02 10:59 UTC, joshuachp commented on examples/individual_properties/main.rs
> +use std::io::BufReader;
```suggestion
```

2023-05-02 10:59 UTC, joshuachp commented on examples/individual_properties/main.rs
> +    let cfg: Config = serde_json::from_reader(BufReader::new(file)).unwrap();
```suggestion
    let file = std::fs::read_to_string("./examples/individual_properties/configuration.json").unwrap();
    let cfg: Config = serde_json::from_str(&file).unwrap();
```

2023-05-02 10:59 UTC, joshuachp commented on examples/individual_properties/main.rs
> +    let db = AstarteSqliteDatabase::new(this_file.to_str().unwrap()).await?;
```suggestion
    let db = AstarteSqliteDatabase::new("./examples/individual_properties/astarte-example-db.sqlite").await?;
```

2023-05-02 10:59 UTC, joshuachp commented on examples/individual_properties/main.rs
> +    let db = AstarteSqliteDatabase::new(this_file.to_str().unwrap()).await?;
This could be also improved by saving the database to a temporary directory with `tempdir` that would be cleaned when the example finishes

2023-05-02 10:59 UTC, joshuachp commented on examples/object_datastream/main.rs
> +    let cfg: Config = serde_json::from_reader(BufReader::new(file)).unwrap();
```suggestion
    let file = std::fs::read_to_string("./examples/object_datastream/configuration.json").unwrap();
    let cfg: Config = serde_json::from_str(&file).unwrap();
```

2023-05-02 10:59 UTC, joshuachp commented on examples/object_datastream/main.rs
> +use std::io::BufReader;
```suggestion
```

2023-05-02 10:59 UTC, joshuachp commented on examples/registration/main.rs
> +use std::io::BufReader;
```suggestion
```

2023-05-02 10:59 UTC, joshuachp commented on examples/registration/main.rs
> +    let cfg: Config = serde_json::from_reader(BufReader::new(file)).unwrap();
```suggestion
    let file = std::fs::read_to_string("./examples/registration/configuration.json").unwrap();
    let cfg: Config = serde_json::from_str(&file).unwrap();
```

2023-05-03 08:12 UTC, joshuachp approved these changes

2023-05-05 13:00 UTC, harlem88 requested changes

2023-05-05 13:00 UTC, harlem88 commented on examples/individual_datastream/interfaces/org.astarte-platform.rust.individual-datastream.ServerDatastream.json
> +    "interface_name": "org.astarte-platform.rust.examples.individual-datastream.ServerDatastream",
same above

2023-05-05 13:00 UTC, harlem88 commented on examples/individual_datastream/main.rs
> + * Copyright 2021 SECO Mind Srl
```suggestion
 * Copyright 2023 SECO Mind Srl
```

2023-05-05 13:00 UTC, harlem88 commented on examples/individual_properties/README.md
> +Copyright 2021,2022 SECO Mind Srl
```suggestion
Copyright 2023 SECO Mind Srl
```

2023-05-05 13:00 UTC, harlem88 commented on examples/individual_properties/main.rs
> + * Copyright 2021 SECO Mind Srl
```suggestion
 * Copyright 2023 SECO Mind Srl
```

2023-05-05 13:00 UTC, harlem88 commented on examples/object_datastream/README.md
> +Copyright 2021,2022 SECO Mind Srl
```suggestion
Copyright 2023 SECO Mind Srl
```

2023-05-05 13:00 UTC, harlem88 commented on examples/object_datastream/main.rs
> + * Copyright 2021 SECO Mind Srl
```suggestion
 * Copyright 2023 SECO Mind Srl
```

2023-05-05 14:17 UTC, sorru94 commented on examples/individual_datastream/interfaces/org.astarte-platform.rust.individual-datastream.DeviceDatastream.json
> +    "interface_name": "org.astarte-platform.rust.examples.individual-datastream.DeviceDatastream",
I would change the name of the file as the interface name is used this way everywhere.

2023-05-09 07:46 UTC, harlem88 requested changes

2023-05-09 07:46 UTC, harlem88 commented on examples/individual_datastream/README.md
> +Copyright 2021,2022 SECO Mind Srl
```suggestion
Copyright 2023 SECO Mind Srl
```

2023-05-09 07:46 UTC, harlem88 commented on examples/README.md
> +Copyright 2021,2022 SECO Mind Srl
```suggestion
Copyright 2023 SECO Mind Srl
```

2023-05-10 08:51 UTC, harlem88 approved these changes

2023-05-10 10:38 UTC, merged