Conversion from astarte type
astarte-platform/astarte-device-sdk-rust pull request #96
Opened 2022-12-21 11:46 UTC by sorru94

Implement the `TryFrom` trait for the base types from an `AstarteType`.
Closes #88.

2022-12-21 12:09 UTC, sorru94 commented on src/types.rs
> +    }
I made two separate macros here mostly because I could not figure out how to match a pattern like:
```
Vec::<u8>
```
Any ideas?

2022-12-21 14:21 UTC, sorru94 commented
I didn't implement the `TryFrom` from `AstarteType` to a `&str` since it would create problems with the lifetime of the `&str`.

2022-12-23 15:15 UTC, harlem88 requested changes

2022-12-23 15:15 UTC, harlem88 commented on src/lib.rs
> +    ConversionError,
Remove the trailing part that contains `Error`

2023-01-11 14:51 UTC, FrancescoVaiani approved these changes

2023-01-11 16:28 UTC, harlem88 approved these changes

2023-01-11 17:01 UTC, merged